### ISSUE TITLE
地区外のポリゴンを出力しないでほしい

### ISSUE THREAD

**Issue by koukita** [JDA-DM/mojxml2geojson#11]
地区外のポリゴンがあると、隣のレイヤと地物が合わなくなり、削除する手間が必要となるため、「地区外-xxxxxx」という地物は変換の対象としないでほしいです。

**Comment by keichan34** [comment]
`--exclude` というオプションを指定すれば、 `地区外` と `別図` が出力から除かれます。

https://github.com/JDA-DM/mojxml2geojson/blob/af36568ef5e846efa106d0f5f746d5efd679f58b/src/package/MojXMLtoGeoJSON.py#L27-L30

他のフィルターをかけたい場合は別途削除する必要ありそうですね。私は基本的にndgeojson使っているので `jq` だと `jq -cr 'if (.properties."地番" | test("^[0-9]")) then . else empty end' input.ndgeojson > output.ndgeojson` で地番が数字で始まるfeatureに絞ることができてるんですが、そのままのGeoJSONのFeatureCollectionだとちょっと改造が必要です

**Comment by koukita** [comment]
オプションがあったのですね。ありがとうございました。
