### ISSUE TITLE
xmlに文字化けと思われる箇所がある

### ISSUE THREAD

**Issue by YusukeOhori** [JDA-DM/mojxml2geojson#12]
宮崎県西臼杵郡五ケ瀬町のxmlファイル45443-3503-27.xmlの、654697行目あたりから文字化けしていると思われる箇所があり、xmlをパースすることができません

**Comment by koswatana** [comment]
こちら既知の現象で、全データ中該当のXMLにのみ制御文字が含まれています。
意図したものであるのか不明なのでデータ提供元である法務省に共有済みです。

**Comment by koswatana** [comment]
元データが直ったことを確認
https://github.com/digital-go-jp/mojxml2geojson/issues/20#issuecomment-1782816668
