### ISSUE TITLE
レコードの一部欠損

### ISSUE THREAD

**Issue by YusukeOhori** [JDA-DM/mojxml2geojson#13]
名古屋市守山区のデータに欠損がありました

・下記のgeometryは四角形の土地であるのに対し、座標が3点しかない
[[[[136.938942963, 35.213606745], [136.938942965, 35.213609928], [136.938942963, 35.213606745]]]]
・加えて１番目の座標[136.938942963, 35.213606745]と3番目の座標[136.938942963, 35.213606745]は全く同一であり、直線状になっている
・そのため、geojson変換においてmojGeojsonの処理を行うとNoneType' object has no attribute 'GetY'が出る

以下該当のgeometryデータ
--------------------------------------------------------------------------------------------------
{"geometry": {"coordinates": [[[[136.938942963, 35.213606745], [136.938942965, 35.213609928], [136.938942963, 35.213606745]]]], "type": "MultiPolygon"}, "properties": {"version": "ver1.0", "\u4e01\u76ee\u30b3\u30fc\u30c9": "003", "\u4e01\u76ee\u540d": "\uff13\u4e01\u76ee", "\u4e88\u5099\u30b3\u30fc\u30c9": "00", "\u4e88\u5099\u540d": null, "\u5730\u56f3\u540d": "MET14032", "\u5730\u56f3\u756a\u53f7": "A01 24-4", "\u5730\u756a": "\u6c34-71", "\u5927\u5b57\u30b3\u30fc\u30c9": "636", "\u5927\u5b57\u540d": "\u702c\u53e4", "\u5c0f\u5b57\u30b3\u30fc\u30c9": "0000", "\u5c0f\u5b57\u540d": null, "\u5e02\u533a\u753a\u6751\u30b3\u30fc\u30c9": "23113", "\u5e02\u533a\u753a\u6751\u540d": "\u540d\u53e4\u5c4b\u5e02\u5b88\u5c71\u533a", "\u5ea7\u6a19\u5024\u7a2e\u5225": "\u6e2c\u91cf\u6210\u679c", "\u5ea7\u6a19\u7cfb": "\u516c\u5171\u5ea7\u6a197\u7cfb", "\u6e2c\u5730\u7cfb\u5224\u5225": "\u5909\u63db", "\u7b46ID": "H000001227", "\u7b46\u754c\u672a\u5b9a\u69cb\u6210\u7b46": null, "\u7cbe\u5ea6\u533a\u5206": "\u7532\u4e8c", "\u7e2e\u5c3a\u5206\u6bcd": "500"}, "type": "Feature"}

**Comment by koswatana** [comment]
該当データのG空間情報センターのURLかファイル名をお示しいただけますでしょうか

**Comment by YusukeOhori** [comment]
こちらになります
ファイル名 : 23113-1844.zip
URL : https://www.geospatial.jp/ckan/dataset/houmusyouchizu-2022-1-1130

**Comment by koswatana** [comment]
unescape
```
{"geometry": {"coordinates": [[[[136.938942963, 35.213606745], [136.938942965, 35.213609928], [136.938942963, 35.213606745]]]], "type": "MultiPolygon"}, "properties": {"version": "ver1.0", "丁目コード": "003", "丁目名": "３丁目", "予備コード": "00", "予備名": null, "地図名": "MET14032", "地図番号": "A01 24-4", "地番": "水-71", "大字コード": "636", "大字名": "瀬古", "小字コード": "0000", "小字名": null, "市区町村コード": "23113", "市区町村名": "名古屋市守山区", "座標値種別": "測量成果", "座標系": "公共座標7系", "測地系判別": "変換", "筆ID": "H000001227", "筆界未定構成筆": null, "精度区分": "甲二", "縮尺分母": "500"}, "type": "Feature"}
```

指摘のファイル
23113-1844-44.xml

**Comment by koswatana** [comment]
該当の筆ID`H000001227`


- F000001227
```
		<zmn:GM_Surface id="F000001227">
			<zmn:GM_Surface.patch>
				<zmn:GM_Polygon>
					<zmn:GM_Polygon.boundary>
						<zmn:GM_SurfaceBoundary>
							<zmn:GM_SurfaceBoundary.exterior>
								<zmn:GM_Ring>
									<zmn:GM_CompositeCurve.generator idref="C000007547"/>
									<zmn:GM_CompositeCurve.generator idref="C000007548"/>
								</zmn:GM_Ring>
							</zmn:GM_SurfaceBoundary.exterior>
						</zmn:GM_SurfaceBoundary>
					</zmn:GM_Polygon.boundary>
				</zmn:GM_Polygon>
			</zmn:GM_Surface.patch>
		</zmn:GM_Surface>
```


- C000007547
```
		<zmn:GM_Curve id="C000007547">
			<zmn:GM_OrientablePrimitive.orientation>+</zmn:GM_OrientablePrimitive.orientation>
			<zmn:GM_OrientablePrimitive.primitive idref="C000007547"/>
			<zmn:GM_Curve.segment>
				<zmn:GM_LineString>
					<zmn:GM_LineString.controlPoint>
						<zmn:GM_PointArray.column>
							<zmn:GM_Position.indirect>
								<zmn:GM_PointRef.point idref="P000000966"/>
							</zmn:GM_Position.indirect>
						</zmn:GM_PointArray.column>
						<zmn:GM_PointArray.column>
							<zmn:GM_Position.indirect>
								<zmn:GM_PointRef.point idref="P000000935"/>
							</zmn:GM_Position.indirect>
						</zmn:GM_PointArray.column>
					</zmn:GM_LineString.controlPoint>
				</zmn:GM_LineString>
			</zmn:GM_Curve.segment>
```

- C000007548
```
		<zmn:GM_Curve id="C000007548">
			<zmn:GM_OrientablePrimitive.orientation>+</zmn:GM_OrientablePrimitive.orientation>
			<zmn:GM_OrientablePrimitive.primitive idref="C000007548"/>
			<zmn:GM_Curve.segment>
				<zmn:GM_LineString>
					<zmn:GM_LineString.controlPoint>
						<zmn:GM_PointArray.column>
							<zmn:GM_Position.indirect>
								<zmn:GM_PointRef.point idref="P000000935"/>
							</zmn:GM_Position.indirect>
						</zmn:GM_PointArray.column>
						<zmn:GM_PointArray.column>
							<zmn:GM_Position.indirect>
								<zmn:GM_PointRef.point idref="P000000966"/>
							</zmn:GM_Position.indirect>
						</zmn:GM_PointArray.column>
					</zmn:GM_LineString.controlPoint>
				</zmn:GM_LineString>
			</zmn:GM_Curve.segment>
		</zmn:GM_Curve>
```

- P000000935
```
		<zmn:GM_Point id="P000000935">
			<zmn:GM_Point.position>
				<zmn:DirectPosition>
					<zmn:X>-87218.860</zmn:X>
					<zmn:Y>-20732.256</zmn:Y>
				</zmn:DirectPosition>
			</zmn:GM_Point.position>
		</zmn:GM_Point>
```

- P000000966
```
		<zmn:GM_Point id="P000000966">
			<zmn:GM_Point.position>
				<zmn:DirectPosition>
					<zmn:X>-87219.213</zmn:X>
					<zmn:Y>-20732.257</zmn:Y>
				</zmn:DirectPosition>
			</zmn:GM_Point.position>
		</zmn:GM_Point>
```

**Comment by koswatana** [comment]
- 直線上になるのは元のXMLデータに起因、コンバータは意図通り処理している
- `NoneType' object has no attribute 'GetY'`は再現せず

**Comment by koswatana** [comment]
元データに起因するためClose
