### ISSUE TITLE
Invalid JSON file: Error: Invalid LngLat latitude value: must be between -90 and 90

### ISSUE THREAD

**Issue by RubyLucy** [JDA-DM/mojxml2geojson#16]
`13220-0128-71.xml`から`13220-0128-71.geojson`への変換はできましたが、ファイルの中身に不具合がありそうで当該geojsonファイルの読み込みに失敗しました。

<img width="1298" alt="image" src="https://user-images.githubusercontent.com/34054405/217748639-ff330620-24d4-434f-9696-eb1ca8b26f78.png">

どうか修正してください。

**Comment by keichan34** [comment]
[以前似たようなバグ報告が英語](https://github.com/JDA-DM/mojxml2geojson/issues/7#issuecomment-1404451218)でもありましたが、「任意座標系」（地図XMLの最初の方に `<座標系>任意座標系</座標系>` となっている）場合は、基準点がないので世界座標系に変換できなく、地図XMLファイルに入っている座標をそのままGeoJSONに出力する仕様だそうです。

**Comment by RubyLucy** [comment]
> [以前似たようなバグ報告が英語](https://github.com/JDA-DM/mojxml2geojson/issues/7#issuecomment-1404451218)でもありましたが、「任意座標系」（地図XMLの最初の方に `<座標系>任意座標系</座標系>` となっている）場合は、基準点がないので世界座標系に変換できなく、地図XMLファイルに入っている座標をそのままGeoJSONに出力する仕様だそうです。

`13220-0128-71.xml`を開き、手動で`<座標系>任意座標系</座標系>`の行を`<座標系>公共座標9系</座標系>`に編集し、再度geojsonに変換したら、相変わらずエラーが出ました。
`Invalid JSON file: Error: Invalid LngLat latitude value: must be between -90 and 90`

**元々のxmlファイルに不具合があったのか、それとも本ツール変換のロジックにバグがあるのか、どなたか確認をお願いします。**

<img width="1313" alt="image" src="https://user-images.githubusercontent.com/34054405/219615932-18184c3e-ad6c-4c5e-8f56-24b99ddacfc8.png">


### 更新

https://geojson.io/
のキャッシュをクリアして再度上記のgeojsonファイルを読み込ませたら、無事に開きましたが、背景の地図がズレています。
やはりバグがあったかと思います。
どなたか修正をお願いします。

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/34054405/219618720-04e9a1bc-a682-4c3f-95c5-6a19de1198a8.png">

**Comment by j416dy** [comment]
最後の画像が出ている時点で正常挙動と思われます。
元データは本来任意座標系なので、地図の背景と合わせられない(測量制度が低く、原点が不明な)データです。

**Comment by koswatana** [comment]
`13220-0128-71.xml`のデータを確認しましたが、座標系が任意座標系であるためコンバータとしては想定通りの動作です。
