### ISSUE TITLE
コマンドラインから複数ファイルを処理するときファイル名に空白文字などを含む可能性を考慮する

### ISSUE THREAD

**Issue by takedah** [JDA-DM/mojxml2geojson#2]
README.md の Usage について少しだけ気になった部分があります。
複数の登記所備付地図データを処理する例の記載があり、登記所備付地図データの格納ディレクトリで ls コマンドの出力をパイプで xargs に渡して処理するようになっています。
しかし、ls コマンドの出力をパイプで xargs に渡す場合で、ファイル名に空白文字や改行文字などの特殊文字を含んでいる場合、期待した結果が得られないと思われます。
そこで、パイプは使わず、次の例のように find コマンドの -exec オプションを使用するように変更するのはどうでしょうか？（元の ls を使う例の出力に合わせてカレントディレクトリのみ処理するようにしています。）
```bash
find . -type d ! -name . -prune -o -name "*.xml" -exec mojxml2geojson {} +
```
法務省の登記所備付地図データのファイル名に空白文字を含むことはなさそうなので考え過ぎかもしれませんが、念のためと思い提案しました。よろしくお願いします。

**Comment by kobakazu0429** [comment]
ダブルクォテーションで囲うことで解決しそうな気がしますがいかがでしょうか？

README.md の Parallel Processingに書かれている
```
ls -1 *.xml|xargs -P100 -I{} mojxml2geojson {}
```
の場合
```
ls -1 *.xml|xargs -P100 -I{} mojxml2geojson "{}"
```
のようなイメージです。

こちらであれば空白などに対処できるかと思います。

**Comment by takedah** [comment]
ありがとうございます、空白文字を含むファイルの場合、ダブルクォーテーションで囲うことで解決しました。
ファイル名に改行文字を含む場合は、これでもエラーとなってしまいました。ファイル名に改行が入る状況はさすがに考慮する必要はないと思いつつ、xargs の 0 オプションを使えばファイル名に空白文字や改行文字が含まれる場合でも対応できました。
```bash
find . -type d ! -name . -prune -o -name "*.xml" -print0 | xargs -0I{} mojxml2geojson {}
```
